//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhomProject.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int ProductId { get; set; }
        public string Name { get; set; }
        [AllowHtml] // <--- ADD THIS LINE
        public string Description { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> OldPrice { get; set; }
        public int CategoryId { get; set; }
        public decimal Rating { get; set; }
        public int ReviewCount { get; set; }
        public string ThumbnailUrl { get; set; }
        public string MainImageUrl { get; set; }
        public bool IsActive { get; set; }
        public int StockQuantity { get; set; }


        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
